# This workflow is managed by gh actions-lock.
# SPDX-License-Identifier: MPL-2.0
# // Copyright (c) Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
# SPDX-License-Identifier: MPL-2.0
name: Secret Scanner
on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  actions: read
  contents: read
jobs:
  scan:
    permissions:
      contents: read
    uses: hyperpolymath/standards/.github/workflows/secret-scanner-reusable.yml@e9fa12b965897f485f8ec143e048a424b52f689a
    secrets: inherit
